<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="FontAwesome.Sharp" Version="6.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BookLibrary.Entities\BookLibrary.Entities.csproj" />
    <ProjectReference Include="..\BookLibrary.DAL\BookLibrary.DAL.csproj" />
    <ProjectReference Include="..\BookLibrary.BLL\BookLibrary.BLL.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>