<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Content Include="Assets\buklib.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\add.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FontAwesome.Sharp" Version="6.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BookLibrary.Entities\BookLibrary.Entities.csproj" />
    <ProjectReference Include="..\BookLibrary.DAL\BookLibrary.DAL.csproj" />
    <ProjectReference Include="..\BookLibrary.BLL\BookLibrary.BLL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>Assets\buklib.ico</ApplicationIcon>
  </PropertyGroup>

</Project>